# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Samuel Campbell
tagline:             ''
description:         ''
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Samuel Campbell
  url:               
  email:             samuel.pcampbell@gmail.com

# Custom vars
version:             1.0.0
